# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import Dict, List, Union, Optional
from typing_extensions import Literal, Annotated, TypeAlias

from ..._utils import PropertyInfo
from ..._models import BaseModel

__all__ = [
    "CompletionCreateResponse",
    "Choice",
    "ChoiceMessage",
    "ChoiceMessageFunctionCall",
    "ChoiceMessageToolCall",
    "ChoiceMessageToolCallFunction",
    "ChoiceMessageToolCallFunctionFunction",
    "ChoiceMessageToolCallCustom",
    "ChoiceMessageToolCallCustomCustom",
    "ChoiceLogprobs",
    "ChoiceLogprobsContent",
    "ChoiceLogprobsContentTopLogprob",
    "ChoiceLogprobsRefusal",
    "ChoiceLogprobsRefusalTopLogprob",
    "Usage",
    "UsageCompletionTokensDetails",
    "UsagePromptTokensDetails",
]


class ChoiceMessageFunctionCall(BaseModel):
    """Deprecated: the name and arguments of a function that should be called."""

    arguments: str
    """Arguments to pass to the function as a JSON string."""

    name: str
    """Name of the function to call."""


class ChoiceMessageToolCallFunctionFunction(BaseModel):
    """Function call details."""

    arguments: str
    """Arguments to pass to the function as a JSON string."""

    name: str
    """Name of the function to call."""


class ChoiceMessageToolCallFunction(BaseModel):
    """Tool call specification for OpenAI-compatible chat completion responses."""

    id: str
    """Unique identifier for the tool call."""

    function: ChoiceMessageToolCallFunctionFunction
    """Function call details."""

    type: Literal["function"]
    """Must be 'function' to identify this as a function call."""


class ChoiceMessageToolCallCustomCustom(BaseModel):
    """The custom tool that the model called."""

    input: str
    """The input for the custom tool call generated by the model."""

    name: str
    """The name of the custom tool to call."""


class ChoiceMessageToolCallCustom(BaseModel):
    """A call to a custom tool created by the model."""

    id: str
    """The ID of the tool call."""

    custom: ChoiceMessageToolCallCustomCustom
    """The custom tool that the model called."""

    type: Literal["custom"]
    """The type of the tool. Always 'custom'."""


ChoiceMessageToolCall: TypeAlias = Annotated[
    Union[ChoiceMessageToolCallFunction, ChoiceMessageToolCallCustom], PropertyInfo(discriminator="type")
]


class ChoiceMessage(BaseModel):
    """The message from the model."""

    annotations: Optional[List[Dict[str, object]]] = None
    """Annotations for the message, when applicable."""

    audio: Optional[Dict[str, object]] = None
    """Audio response data when using audio output modality."""

    content: Optional[str] = None
    """The content of the message."""

    function_call: Optional[ChoiceMessageFunctionCall] = None
    """Deprecated: the name and arguments of a function that should be called."""

    refusal: Optional[str] = None
    """The refusal message generated by the model."""

    role: Optional[Literal["assistant"]] = None
    """The role of the message author, always 'assistant' in responses."""

    tool_calls: Optional[List[ChoiceMessageToolCall]] = None
    """The tool calls generated by the model."""


class ChoiceLogprobsContentTopLogprob(BaseModel):
    """
    The top log probability for a token from an OpenAI-compatible chat completion response.
    """

    token: str
    """The token."""

    logprob: float
    """The log probability of the token."""

    bytes: Optional[List[int]] = None
    """The bytes for the token."""


class ChoiceLogprobsContent(BaseModel):
    """
    The log probability for a token from an OpenAI-compatible chat completion response.
    """

    token: str
    """The token."""

    logprob: float
    """The log probability of the token."""

    bytes: Optional[List[int]] = None
    """The bytes for the token."""

    top_logprobs: Optional[List[ChoiceLogprobsContentTopLogprob]] = None
    """The top log probabilities for the token."""


class ChoiceLogprobsRefusalTopLogprob(BaseModel):
    """
    The top log probability for a token from an OpenAI-compatible chat completion response.
    """

    token: str
    """The token."""

    logprob: float
    """The log probability of the token."""

    bytes: Optional[List[int]] = None
    """The bytes for the token."""


class ChoiceLogprobsRefusal(BaseModel):
    """
    The log probability for a token from an OpenAI-compatible chat completion response.
    """

    token: str
    """The token."""

    logprob: float
    """The log probability of the token."""

    bytes: Optional[List[int]] = None
    """The bytes for the token."""

    top_logprobs: Optional[List[ChoiceLogprobsRefusalTopLogprob]] = None
    """The top log probabilities for the token."""


class ChoiceLogprobs(BaseModel):
    """The log probabilities for the tokens in the message."""

    content: Optional[List[ChoiceLogprobsContent]] = None
    """The log probabilities for the tokens in the message."""

    refusal: Optional[List[ChoiceLogprobsRefusal]] = None
    """The log probabilities for the refusal tokens."""


class Choice(BaseModel):
    """A choice from an OpenAI-compatible chat completion response."""

    finish_reason: Literal["stop", "length", "tool_calls", "content_filter", "function_call"]
    """The reason the model stopped generating."""

    index: int
    """The index of the choice."""

    message: ChoiceMessage
    """The message from the model."""

    logprobs: Optional[ChoiceLogprobs] = None
    """The log probabilities for the tokens in the message."""


class UsageCompletionTokensDetails(BaseModel):
    """Detailed breakdown of output token usage."""

    reasoning_tokens: Optional[int] = None
    """Number of tokens used for reasoning (o1/o3 models)."""


class UsagePromptTokensDetails(BaseModel):
    """Detailed breakdown of input token usage."""

    cached_tokens: Optional[int] = None
    """Number of tokens retrieved from cache."""


class Usage(BaseModel):
    """Token usage information for the completion."""

    completion_tokens: Optional[int] = None
    """Number of tokens in the completion."""

    completion_tokens_details: Optional[UsageCompletionTokensDetails] = None
    """Detailed breakdown of output token usage."""

    prompt_tokens: Optional[int] = None
    """Number of tokens in the prompt."""

    prompt_tokens_details: Optional[UsagePromptTokensDetails] = None
    """Detailed breakdown of input token usage."""

    total_tokens: Optional[int] = None
    """Total tokens used (prompt + completion)."""


class CompletionCreateResponse(BaseModel):
    """Response from an OpenAI-compatible chat completion request."""

    id: str
    """The ID of the chat completion."""

    choices: List[Choice]
    """List of choices."""

    created: int
    """The Unix timestamp in seconds when the chat completion was created."""

    model: str
    """The model that was used to generate the chat completion."""

    object: Optional[Literal["chat.completion"]] = None
    """The object type."""

    service_tier: Optional[str] = None
    """The service tier that was used for this response."""

    system_fingerprint: Optional[str] = None
    """System fingerprint for this completion."""

    usage: Optional[Usage] = None
    """Token usage information for the completion."""
