#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

if [[ -n "$1" && "$1" != '--'* ]]; then
  URL="$1"
  shift
else
  URL="$(grep 'openapi_spec_url' .stats.yml | cut -d' ' -f2)"
fi

# Check if the URL is empty
if [ -z "$URL" ]; then
  echo "Error: No OpenAPI spec path/url provided or found in .stats.yml"
  exit 1
fi

# download spec into a temp file and then modify it
SPEC_PATH="$(mktemp)"
echo "==> Downloading spec from ${URL} to ${SPEC_PATH}"
curl -s "$URL" -o "$SPEC_PATH"

echo "==> Modifying SSE schemas for the mock server"
yq -i '(.. | select(has("text/event-stream")).["text/event-stream"].schema) = {"type": "string"}' "$SPEC_PATH"
echo "==> Starting mock server with file ${SPEC_PATH}"

# Run prism mock on the given spec
if [ "$1" == "--daemon" ]; then
  npm exec --package=@mockoon/cli@9.3.0 -- mockoon-cli start --data "$SPEC_PATH" --port 4010 &>.mockoon.log &

  # Wait for server to come online
  echo -n "Waiting for server"
  while ! grep -q "Error: \|Server started on port 4010" ".mockoon.log"; do
    echo -n "."
    sleep 0.1
  done

  if grep -q "Error: " ".mockoon.log"; then
    cat .mockoon.log
    exit 1
  fi

  echo
else
  npm exec --package=@mockoon/cli@9.3.0 -- mockoon-cli start --data "$SPEC_PATH" --port 4010
fi
